// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import java.util.*;
import java.util.concurrent.TimeUnit;


public class TesteBuscaBlog {

    private WebDriver driver;

    // iniciar
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "drivers/chromedriver.exe");
        driver = new ChromeDriver();
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(80000, TimeUnit.MILLISECONDS);
    }

    // finalizar
    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void buscaConexao() {
        driver.get("https://www.soc.com.br/blog-de-sst/");
        driver.findElement(By.cssSelector(".elementor-search-form__container:nth-child(1) > .elementor-search-form__input")).click();
        driver.findElement(By.cssSelector(".elementor-search-form__container:nth-child(1) > .elementor-search-form__input")).sendKeys("SOC");
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".elementor-search-form__submit > .fas"));
            assert(elements.size() > 0);
        }
        driver.findElement(By.cssSelector(".elementor-search-form__submit > .fas")).click();
        //driver.findElement(By.xpath("//a[contains(text(),'Software de SST: entenda a importância para o eSOCial')]")).click();
    }
}
